server:
  port: 8082
spring:
  application:
    name: product-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  euraka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
